- name: Wait for workflow job to complete
  hosts: localhost
  gather_facts: false

  vars:
    headers:
      Authorization: "Bearer {{ tower_token }}"
      Content-Type: "application/json"

  tasks:

    - name: Query workflow jobs for template
      uri:
        url: >-
          {{ tower_url }}/api/v2/workflow_jobs/
          ?workflow_job_template={{ workflow_template_id }}
          &order_by=-created
        method: GET
        headers: "{{ headers }}"
        return_content: true
        validate_certs: false
      register: workflow_jobs
      until: >
        workflow_jobs.json.results
        | selectattr('limit', 'equalto', limit_host)
        | list
        | length > 0
      retries: "{{ poll_retries }}"
      delay: "{{ poll_interval }}"

    - name: Pick latest matching workflow job
      set_fact:
        matched_job: >-
          {{
            workflow_jobs.json.results
            | selectattr('limit', 'equalto', limit_host)
            | list
            | first
          }}

    - name: Print matched workflow job
      debug:
        msg:
          - "Workflow Job ID: {{ matched_job.id }}"
          - "Status: {{ matched_job.status }}"
          - "Created: {{ matched_job.created }}"

    - name: Wait for workflow job to finish
      uri:
        url: "{{ tower_url }}/api/v2/workflow_jobs/{{ matched_job.id }}/"
        method: GET
        headers: "{{ headers }}"
        return_content: true
        validate_certs: false
      register: workflow_job_status
      until: workflow_job_status.json.status in ['successful', 'failed', 'error', 'canceled']
      retries: "{{ poll_retries }}"
      delay: "{{ poll_interval }}"

    - name: Fail if workflow job did not succeed
      fail:
        msg: >-
          Workflow job {{ matched_job.id }} finished with status
          {{ workflow_job_status.json.status }}
      when: workflow_job_status.json.status != 'successful'

    - name: Workflow job succeeded
      debug:
        msg: "Workflow job {{ matched_job.id }} completed successfully"
