- name: Wait for workflow job to complete
  hosts: localhost
  gather_facts: false

  vars:
    headers:
      Authorization: "Bearer {{ tower_token }}"
      Content-Type: "application/json"

  tasks:
- name: Record workflow launch anchor time
  set_fact:
    launch_anchor_time: "{{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%SZ') }}"

- name: Query workflow jobs for template (after launch time)
  uri:
    url: >-
      {{ tower_url }}/api/v2/workflow_jobs/
      ?workflow_job_template={{ workflow_template_id }}
      &order_by=-created
    method: GET
    headers: "{{ headers }}"
    return_content: true
    validate_certs: false
  register: workflow_jobs
  until: >
    (
      workflow_jobs.json.results
      | selectattr('limit', 'equalto', limit_host)
      | selectattr('created', '>=', launch_anchor_time)
      | list
      | length
    ) > 0
  retries: "{{ poll_retries }}"
  delay: "{{ poll_interval }}"
  
    - name: Query workflow jobs for template
      uri:
        url: >-
          {{ tower_url }}/api/v2/workflow_jobs/
          ?workflow_job_template={{ workflow_template_id }}
          &order_by=-created
        method: GET
        headers: "{{ headers }}"
        return_content: true
        validate_certs: false
      register: workflow_jobs
      until: >
        workflow_jobs.json.results
        | selectattr('limit', 'equalto', limit_host)
        | list
        | length > 0
      retries: "{{ poll_retries }}"
      delay: "{{ poll_interval }}"

    - name: Pick latest matching workflow job
      set_fact:
        matched_job: >-
          {{
            workflow_jobs.json.results
            | selectattr('limit', 'equalto', limit_host)
            | list
            | first
          }}

    - name: Print matched workflow job
      debug:
        msg:
          - "Workflow Job ID: {{ matched_job.id }}"
          - "Status: {{ matched_job.status }}"
          - "Created: {{ matched_job.created }}"

    - name: Wait for workflow job to finish
      uri:
        url: "{{ tower_url }}/api/v2/workflow_jobs/{{ matched_job.id }}/"
        method: GET
        headers: "{{ headers }}"
        return_content: true
        validate_certs: false
      register: workflow_job_status
      until: workflow_job_status.json.status in ['successful', 'failed', 'error', 'canceled']
      retries: "{{ poll_retries }}"
      delay: "{{ poll_interval }}"

    - name: Fail if workflow job did not succeed
      fail:
        msg: >-
          Workflow job {{ matched_job.id }} finished with status
          {{ workflow_job_status.json.status }}
      when: workflow_job_status.json.status != 'successful'

    - name: Workflow job succeeded
      debug:
        msg: "Workflow job {{ matched_job.id }} completed successfully"

- name: Search for Tower workflows matching 'name_icontains'
  uri:
    url: "{{ tower_api_url }}/workflow_job_templates/?name__icontains={{ search_workflow_name }}"
    method: GET
    headers: "{{ tower_headers }}"
    validate_certs: "{{ tower_validate_certs | default(false) }}"
    return_content: yes
    status_code: [200]
  register: tower_workflow_search
  delegate_to: localhost

- name: Set list of matched workflows
  set_fact:
    matched_workflows: "{{ tower_workflow_search.json.results | default([]) }}"

- name: Print matched workflows (name and id)
  debug:
    msg: "Workflow name: {{ item.name }}, Workflow id: {{ item.id }}"
  loop: "{{ matched_workflows }}"
  
- name: Workflow retry loop
  until: workflow_final_status == 'successful'
  retries: "{{ max_retries }}"
  delay: 0
  block:

    - name: Launch workflow
      uri:
        url: "{{ tower_url }}/api/v2/workflow_job_templates/{{ workflow_template_id }}/launch/"
        method: POST
        headers:
          Authorization: "Bearer {{ tower_token }}"
        return_content: true
        validate_certs: false
      register: launch_result

    - name: Wait for workflow
      uri:
        url: "{{ tower_url }}/api/v2/workflow_jobs/{{ launch_result.json.id }}/"
        method: GET
        headers:
          Authorization: "Bearer {{ tower_token }}"
        return_content: true
      register: workflow_status
      until: workflow_status.json.status in
        - successful
        - failed
        - error
        - canceled
      retries: "{{ poll_retries }}"
      delay: "{{ poll_interval }}"

    - set_fact:
        workflow_final_status: "{{ workflow_status.json.status }}"
