---
- name: Get ESXi Volume Mode Information
  hosts: all
  gather_facts: false
  vars:
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    validate_certs: "{{ lookup('env', 'VCENTER_VALIDATE_CERTS') | default('false') | bool }}"
    ansible_password: "{{ lookup('env', 'ESXI_PASSWORD') }}"
  
  tasks:
    - name: Enable SSH service on ESXi host
      community.vmware.vmware_host_service_manager:
        esxi_hostname: "{{ inventory_hostname }}"
        service_name: TSM-SSH
        state: present
      delegate_to: localhost
      ignore_errors: true
      changed_when: false

    - name: List volumes under /vmfs/volumes
      ansible.builtin.shell: ls -1 /vmfs/volumes 2>/dev/null || echo ''
      register: volumes_output
      changed_when: false
      failed_when: false

    - name: Filter volumes starting with 'E:'
      set_fact:
        filtered_volumes: "{{ volumes_output.stdout_lines | default([]) | select('match', '^E:.*') | list }}"

    - name: Initialize volume_results list
      set_fact:
        volume_results: []

    - name: Run vmkfstools command on each filtered volume and extract Mode
      block:
        - name: Run vmkfstools command
          ansible.builtin.shell: vmkfstools -Ph -v1 /vmfs/volumes/{{ volume_name | quote }} 2>&1
          register: vmkfstools_result
          changed_when: false
          failed_when: false

        - name: Extract Mode line from vmkfstools output
          set_fact:
            volume_results: "{{ volume_results + [{
              'vcenter': vcenter_hostname,
              'esxi': inventory_hostname,
              'volume': volume_name,
              'mode': mode_value
            }] }}"
          vars:
            stdout_lines: "{{ vmkfstools_result.stdout_lines | default([]) }}"
            mode_line: "{{ stdout_lines | select('match', '^Mode:.*') | list | first | default('') }}"
            mode_value: "{{ mode_line | regex_replace('^Mode:\\s*', '') | default('N/A') }}"
          when: mode_line != ""
      loop: "{{ filtered_volumes }}"
      loop_control:
        loop_var: volume_name
      when: filtered_volumes | length > 0

    - name: Collect results from all hosts
      set_fact:
        final_results: "{{ final_results | default([]) + hostvars[item].get('volume_results', []) }}"
      loop: "{{ groups['all'] }}"
      run_once: true
      delegate_to: localhost

    - name: Create CSV output file
      ansible.builtin.copy:
        content: |
          vcenter,esxi,volume,mode
          {% for result in final_results | default([]) %}
          {{ result.vcenter }},{{ result.esxi }},{{ result.volume }},{{ result.mode }}
          {% endfor %}
        dest: "./esxi_volume_mode_results.csv"
      run_once: true
      delegate_to: localhost
      when: final_results | default([]) | length > 0

    - name: Display results summary
      ansible.builtin.debug:
        msg: "Processed {{ final_results | default([]) | length }} volumes. Results saved to esxi_volume_mode_results.csv"
      run_once: true
      delegate_to: localhost

    - name: Display all results
      ansible.builtin.debug:
        var: final_results
      run_once: true
      delegate_to: localhost
      when: final_results | default([]) | length > 0

    - name: Disable SSH service on ESXi host
      community.vmware.vmware_host_service_manager:
        esxi_hostname: "{{ inventory_hostname }}"
        service_name: TSM-SSH
        state: stopped
      delegate_to: localhost
      ignore_errors: true

    - name: Display SSH disabled message
      ansible.builtin.debug:
        msg: "SSH service has been disabled on all ESXi hosts"
      run_once: true
      delegate_to: localhost
