---
- name: Get ESXi Volume Mode Information
  hosts: all
  gather_facts: false
  vars:
    vcenter_hostname: "{{ lookup('env', 'VCENTER_HOSTNAME') }}"
    vcenter_username: "{{ lookup('env', 'VCENTER_USERNAME') }}"
    vcenter_password: "{{ lookup('env', 'VCENTER_PASSWORD') }}"
    validate_certs: "{{ lookup('env', 'VCENTER_VALIDATE_CERTS') | default('false') | bool }}"
    ansible_password: "{{ lookup('env', 'ESXI_PASSWORD') }}"
  
  tasks:
    - name: Enable SSH service on ESXi host
      community.vmware.vmware_host_service_manager:
        esxi_hostname: "{{ inventory_hostname }}"
        service_name: TSM-SSH
        state: present
      delegate_to: localhost
      ignore_errors: true
      changed_when: false

    - name: List volumes under /vmfs/volumes
      ansible.builtin.shell: ls -1 /vmfs/volumes 2>/dev/null || echo ''
      register: volumes_output
      changed_when: false
      failed_when: false

    - name: Filter volumes starting with 'E:'
      set_fact:
        filtered_volumes: "{{ volumes_output.stdout_lines | default([]) | select('match', '^E:.*') | list }}"

    - name: Initialize volume_results list
      set_fact:
        volume_results: []

    - name: Run vmkfstools command on each filtered volume
      ansible.builtin.shell: vmkfstools -Ph -v1 /vmfs/volumes/{{ volume_name | quote }} 2>&1
      register: vmkfstools_output
      loop: "{{ filtered_volumes }}"
      loop_control:
        loop_var: volume_name
      changed_when: false
      failed_when: false
      when: filtered_volumes | length > 0

    - name: Extract Mode line from vmkfstools output
      no_log: true
      set_fact:
        volume_results: "{{ volume_results + [{
          'vcenter': vcenter_hostname,
          'esxi': inventory_hostname,
          'volume': item.item | default(item.volume_name | default('unknown')),
          'mode': mode_value
        }] }}"
      vars:
        stdout_lines: "{{ item.stdout_lines | default([]) }}"
        mode_line: "{{ stdout_lines | select('match', '^Mode:.*') | list | first | default('') }}"
        mode_value: "{{ mode_line | regex_replace('^Mode:\\s*', '') | default('N/A') }}"
      loop: "{{ vmkfstools_output.results | default([]) }}"
      loop_control:
        loop_var: item
      when:
        - filtered_volumes | length > 0
        - mode_line != ""

    - name: Collect results from all hosts
      set_fact:
        final_results: "{{ final_results | default([]) + hostvars[item].get('volume_results', []) }}"
      loop: "{{ groups['all'] }}"
      run_once: true
      delegate_to: localhost

    - name: Set CSV file path
      set_fact:
        csv_file_path: "./esxi_volume_mode_results.csv"
      run_once: true
      delegate_to: localhost

    - name: Check if CSV file already exists
      ansible.builtin.stat:
        path: "{{ csv_file_path }}"
      register: csv_stat
      run_once: true
      delegate_to: localhost

    - name: Build CSV data lines from results
      set_fact:
        csv_data_lines: "{{ (csv_data_lines | default([])) + ['%s,%s,%s,%s' | format(item.vcenter, item.esxi, item.volume, item.mode)] }}"
      loop: "{{ final_results | default([]) }}"
      loop_control:
        loop_var: item
      run_once: true
      delegate_to: localhost
      when: final_results | default([]) | length > 0

    - name: Create CSV file with header if not exists
      ansible.builtin.copy:
        content: |
          vcenter,esxi,volume,mode
          {% for line in csv_data_lines %}
          {{ line }}
          {% endfor %}
        dest: "{{ csv_file_path }}"
      when:
        - final_results | default([]) | length > 0
        - not csv_stat.stat.exists
      run_once: true
      delegate_to: localhost

    - name: Append data lines to existing CSV file (no header)
      ansible.builtin.shell: |
        printf '%s\n' "{{ csv_data_lines | join('\n') }}" >> {{ csv_file_path }}
      args:
        executable: /bin/bash
      when:
        - final_results | default([]) | length > 0
        - csv_stat.stat.exists
      run_once: true
      delegate_to: localhost

    - name: Display results summary
      ansible.builtin.debug:
        msg: "Processed {{ final_results | default([]) | length }} volumes. Results saved to esxi_volume_mode_results.csv"
      run_once: true
      delegate_to: localhost

    - name: Display all results
      ansible.builtin.debug:
        var: final_results
      run_once: true
      delegate_to: localhost
      when: final_results | default([]) | length > 0

    - name: Disable SSH service on ESXi host
      community.vmware.vmware_host_service_manager:
        esxi_hostname: "{{ inventory_hostname }}"
        service_name: TSM-SSH
        state: absent
      delegate_to: localhost
      ignore_errors: true

    - name: Display SSH disabled message
      ansible.builtin.debug:
        msg: "SSH service has been disabled on all ESXi hosts"
      run_once: true
      delegate_to: localhost
